#!/usr/bin/env ruby

ROOT = Dir.pwd

require 'yaml'
require 'pry'
require "#{ROOT}/lib/params"
require "#{ROOT}/lib/db_setup/command_executer"

# Generate params from argument
params = Params.new(ARGV).generate

# Set up the database
DbSetup::CommandExecuter.new(params).generate.execute
